#!/bin/sh
# Writes src/hello/assets.gleam: the shared template, the index URL and the OG
# card as base64 constants, so they compile into the BEAM modules and the
# server never reads Cloud's ephemeral filesystem. Gleam has no compile-time
# file embedding, and base64 keeps the three blobs valid Gleam string literals.
set -eu
out=src/hello/assets.gleam
{
    printf '//// Generated by gen-assets.sh. Do not edit, and do not commit:\n'
    printf '//// the OG card it carries is built per-commit by tools/ogen.\n\n'
    printf 'pub const page = "%s"\n\n' "$(base64 -w0 shared/page.html)"
    printf 'pub const index_url = "%s"\n\n' "$(base64 -w0 shared/index-url.txt)"
    printf 'pub const og_png = "%s"\n' "$(base64 -w0 og.png)"
} > "$out"
echo "gen-assets: wrote $out ($(wc -c < "$out") bytes)"
