! Generates assets.f90: the shared HTML template, the index URL and the OG card,
! as hexadecimal string constants.
!
! Fortran has no equivalent of `include_str!` or `go:embed`, and the obvious
! workarounds both break on this input: a character literal cannot carry the
! apostrophes in shared/page.html without doubling every one of them, and an
! array constructor of 50,000 `achar()` calls makes gfortran chew for a long
! time. Hex in fixed-length chunks compiles in well under a second and is
! exactly reversible, so the binary still carries its own assets and reads
! nothing from disk -- Cloud's filesystem is ephemeral.
!
! Written in Fortran on purpose: the branch builds Fortran with Fortran.
program genassets
   implicit none
   integer, parameter :: chunk = 2048     ! hex characters per line
   integer :: out

   open (newunit=out, file='assets.f90', status='replace', action='write')
   write (out, '(a)') '! GENERATED by genassets.f90 -- do not edit.'
   write (out, '(a)') 'module assets'
   write (out, '(a)') '   implicit none'
   write (out, '(a)') '   integer, parameter :: asset_chunk = 2048'
   call emit(out, 'shared/page.html', 'page_html')
   call emit(out, 'shared/index-url.txt', 'index_url')
   call emit(out, 'og.png', 'og_png')
   write (out, '(a)') 'end module assets'
   close (out)

contains

   subroutine emit(out, path, name)
      integer, intent(in) :: out
      character(len=*), intent(in) :: path, name
      character(len=1), allocatable :: raw(:)
      character(len=:), allocatable :: hex
      integer :: unit, nbytes, nchunks, i, first, last
      character(len=16), parameter :: digits = '0123456789abcdef'

      open (newunit=unit, file=path, access='stream', form='unformatted', &
            status='old', action='read')
      inquire (unit=unit, size=nbytes)
      allocate (raw(nbytes))
      read (unit) raw
      close (unit)

      allocate (character(len=2*nbytes) :: hex)
      do i = 1, nbytes
         hex(2*i - 1:2*i - 1) = digits(iachar(raw(i))/16 + 1:iachar(raw(i))/16 + 1)
         hex(2*i:2*i) = digits(modulo(iachar(raw(i)), 16) + 1:modulo(iachar(raw(i)), 16) + 1)
      end do

      nchunks = (2*nbytes + chunk - 1)/chunk
      write (out, '(a)') '   integer, parameter :: '//trim(name)//'_bytes = '//itoa(nbytes)
      write (out, '(a)') '   integer, parameter :: '//trim(name)//'_chunks = '//itoa(nchunks)
      write (out, '(a)') '   character(len=asset_chunk), parameter :: '//trim(name)// &
         '_hex('//itoa(nchunks)//') = [ character(len=asset_chunk) :: &'
      do i = 1, nchunks
         first = (i - 1)*chunk + 1
         last = min(i*chunk, 2*nbytes)
         if (i < nchunks) then
            write (out, '(a)') "      '"//hex(first:last)//"', &"
         else
            write (out, '(a)') "      '"//hex(first:last)//"' ]"
         end if
      end do
   end subroutine emit

   function itoa(n) result(s)
      integer, intent(in) :: n
      character(len=:), allocatable :: s
      character(len=16) :: buf
      write (buf, '(i0)') n
      s = trim(buf)
   end function itoa

end program genassets
