#!/bin/sh
# Generates assets.cpy: the shared HTML template, the index URL and the OG card,
# as COBOL WORKING-STORAGE groups built from hexadecimal literals.
#
# COBOL has no equivalent of `include_str!` or `go:embed`, and it cannot read
# the files at run time either -- Cloud's filesystem is ephemeral. What it does
# have is the hexadecimal literal, X"89504e47...", so each file becomes a group
# item whose FILLERs carry it 200 bytes at a time. GnuCOBOL truncates any source line past
# 512 bytes, which caps a chunk at 400 hex characters, and a group item's subordinate FILLERs are
# contiguous, so GROUP(1:LEN) is the original file byte for byte.
set -eu

emit() {
    file="$1"
    name="$2"
    bytes=$(wc -c < "$file" | tr -d ' ')
    printf '01  %s-LEN PIC S9(9) COMP-5 VALUE %s.\n' "$name" "$bytes"
    printf '01  %s-DATA.\n' "$name"
    # `|| [ -n "$hex" ]` matters: tr strips the trailing newline, so fold's last
    # chunk arrives without one and a plain `read` would drop it.
    od -An -v -tx1 "$file" | tr -d ' \n' | fold -w 400 | while IFS= read -r hex || [ -n "$hex" ]; do
        printf '    05  FILLER PIC X(%d) VALUE X"%s".\n' "$(( ${#hex} / 2 ))" "$hex"
    done
}

{
    printf '*> GENERATED by genassets.sh -- do not edit.\n'
    emit shared/page.html PAGE-HTML
    emit shared/index-url.txt INDEX-URL
    emit og.png OG-PNG
} > assets.cpy

wc -c assets.cpy
