#!/usr/bin/perl
# Writes Payload.pm: the shared template, the shared index URL and the OG card
# as base64 string literals, so the packed binary reads none of them from disk.
# Base64 for all three -- the template is full of quotes and sigils, and the OG
# card is binary.
use strict;
use warnings;
use MIME::Base64 qw(encode_base64);

sub slurp { local (@ARGV, $/) = (shift); scalar <> }

my %payload = (
    TEMPLATE  => slurp('shared/page.html'),
    INDEX_URL => slurp('shared/index-url.txt'),
    OG_PNG    => slurp('og.png'),
);
$payload{INDEX_URL} =~ s/\s+\z//;

print <<'HEAD';
package Payload;
# Generated by genpayload.pl. Do not edit; do not commit.
use strict;
use warnings;
use Exporter qw(import);
use MIME::Base64 qw(decode_base64);
our @EXPORT_OK = qw(TEMPLATE INDEX_URL OG_PNG);
HEAD

for my $key (sort keys %payload) {
    print "my \$$key = decode_base64(<<'B64_$key');\n";
    print encode_base64($payload{$key});
    print "B64_$key\n";
    print "sub $key { \$$key }\n";
}
print "1;\n";
