#!/bin/sh
# Writes Sources/app/Payload.swift: the shared template and index URL as raw
# string literals, the OG card as base64. Swift has no include_str!, and an SPM
# resource bundle would mean reading files at run time, which Cloud's ephemeral
# filesystem makes a bad idea.
#
# A raw string literal (#"""..."""#) is used for the template so that nothing
# in the HTML is treated as an escape or an interpolation. It is safe because
# the shared template contains no backslash and no triple quote.
set -eu

test ! -s shared/page.html && { echo "genpayload: shared/page.html is empty" >&2; exit 1; } || true
grep -q '"""' shared/page.html && { echo "genpayload: the template now contains a triple quote; the raw literal below would break" >&2; exit 1; } || true

{
    echo '// Generated by genpayload.sh. Do not edit; do not commit.'
    echo 'let template = #"""'
    cat shared/page.html
    echo '"""#'
    printf 'let indexURL = "%s"\n' "$(tr -d '\n' < shared/index-url.txt)"
    printf 'let ogPNGBase64 = "'
    base64 -w0 og.png
    printf '"\n'
} > Sources/app/Payload.swift
