// Dart has no compile-time file embedding (no include_bytes!/staticRead), so
// this generator turns the three shared inputs into a Dart source file that
// `dart compile exe` then welds into the executable. Run from `dartapp/`:
//
//     dart run tool/embed.dart
//
// Base64 rather than string literals: the OG card is binary, and base64 cannot
// collide with Dart's quoting however the HTML template changes.
import 'dart:convert';
import 'dart:io';

void main() {
  final template = File('../shared/page.html').readAsBytesSync();
  final indexUrl = File('../shared/index-url.txt').readAsBytesSync();
  final ogPng = File('../og.png').readAsBytesSync();

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed.dart. Do not edit, do not commit.')
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("const _template = '${base64Encode(template)}';")
    ..writeln("const _indexUrl = '${base64Encode(indexUrl)}';")
    ..writeln("const _ogPng = '${base64Encode(ogPng)}';")
    ..writeln()
    ..writeln('final String template = utf8.decode(base64Decode(_template));')
    ..writeln('final String indexUrl = utf8.decode(base64Decode(_indexUrl));')
    ..writeln('final Uint8List ogPng = base64Decode(_ogPng);');

  File('bin/embedded.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('embed: wrote bin/embedded.g.dart '
      '(template ${template.length}B, og.png ${ogPng.length}B)');
}
