//// Hello from Gleam, on Laravel Cloud's Go runtime.
////
//// Laravel Cloud runs this binary because the branch carries a `go.mod` at
//// its root, so the environment was detected as Go when it was created and
//// Cloud starts whatever executable the build command left at `./app`. The
//// build command for this environment never compiles any Go: it downloads
//// the binary GitHub Actions built from this commit.
////
//// Nothing on the host is assumed: `./app` is a C launcher carrying a tar.gz
//// of an Erlang release WITH ERTS, which it unpacks under $TMPDIR on first
//// start. The shared template, the index URL and the OG card are base64
//// constants in `hello/assets`, generated by the build, so they live in the
//// BEAM modules and nothing is read from Cloud's ephemeral filesystem.

import envoy
import gleam/bit_array
import gleam/bytes_tree
import gleam/erlang/process
import gleam/http/request
import gleam/http/response
import gleam/int
import gleam/list
import gleam/result
import gleam/string
import hello/assets
import mist
import wisp
import wisp/wisp_mist

const language = "Gleam"

const branch = "gleam"

const repo_url = "https://github.com/artisan-build/hello_cloud"

pub fn main() -> Nil {
  let port =
    envoy.get("PORT")
    |> result.try(int.parse)
    |> result.unwrap(3000)

  wisp.configure_logger()

  let assert Ok(_) =
    wisp_mist.handler(handle_request, wisp.random_string(64))
    |> mist.new
    // Cloud's per-instance nginx proxies to $PORT over an IPv6-only network,
    // so bind the IPv6 wildcard. Linux leaves IPV6_V6ONLY off by default,
    // which makes that socket dual-stack.
    |> mist.bind("::")
    |> mist.port(port)
    |> mist.start

  process.sleep_forever()
}

fn handle_request(req: wisp.Request) -> wisp.Response {
  case request.path_segments(req) {
    ["og.png"] -> og_card()
    _ -> page(req)
  }
}

fn page(req: wisp.Request) -> wisp.Response {
  let host = result.unwrap(request.get_header(req, "host"), "localhost")
  wisp.html_response(render(host), 200)
}

fn og_card() -> wisp.Response {
  wisp.ok()
  |> response.set_header("content-type", "image/png")
  |> response.set_header("cache-control", "public, max-age=3600")
  |> wisp.set_body(wisp.Bytes(bytes_tree.from_bit_array(bytes(assets.og_png))))
}

/// Fills the shared template's seven placeholders.
///
/// `og:image` and `og:url` have to be absolute, so they are built from the
/// request's Host header with a hard-coded https scheme: Cloud terminates TLS
/// upstream and then sends `X-Forwarded-Proto: http` on an https request, so
/// that header cannot be trusted.
fn render(host: String) -> String {
  let base = "https://" <> host
  [
    #("{{LANGUAGE}}", language),
    #("{{BRANCH}}", branch),
    #("{{BRANCH_URL}}", repo_url <> "/tree/" <> branch),
    #("{{OG_IMAGE}}", base <> "/og.png"),
    #("{{PAGE_URL}}", base <> "/"),
    #("{{INDEX_URL}}", string.trim(text(assets.index_url))),
    #("{{EXTRA}}", ""),
  ]
  |> list.fold(text(assets.page), fn(page, pair) {
    string.replace(page, pair.0, pair.1)
  })
}

fn bytes(base64: String) -> BitArray {
  let assert Ok(decoded) = bit_array.base64_decode(base64)
  decoded
}

fn text(base64: String) -> String {
  let assert Ok(decoded) = bit_array.to_string(bytes(base64))
  decoded
}
